//
//  SleepDetailView.swift
//  FlatSleep
//
//  Created by Radomyr Sidenko on 26.05.2026.
//

import SwiftUI

struct SleepDetailView: View {
    let date: Date
    let summary: DailySleepSummary?
    
    private let formatter: DateFormatter = {
        let df = DateFormatter()
        df.dateFormat = "d MMMM yyyy"
        return df
    }()
    
    var body: some View {
        ScrollView {
            VStack(spacing: 20) {
                
                if let summary = summary, summary.totalSleepTime > 0 {
                    
                    HStack(spacing: 20) {
                        VStack(alignment: .leading, spacing: 4) {
                            Text("TIME IN BED")
                                .font(.caption2)
                                .foregroundColor(.secondary)
                                .bold()
                            
                            let totalInBed = summary.totalSleepTime + summary.awakeDuration
                            Text(formatTimeInHoursAndMinutes(totalInBed))
                                .font(.title)
                                .bold()
                                .foregroundColor(.primary)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        
                        VStack(alignment: .leading, spacing: 4) {
                            Text("TIME ASLEEP")
                                .font(.caption2)
                                .foregroundColor(.secondary)
                                .bold()
                            
                            Text(formatTimeInHoursAndMinutes(summary.totalSleepTime))
                                .font(.title)
                                .bold()
                                .foregroundColor(.indigo)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding()
                    .background(Color(.secondarySystemBackground))
                    .cornerRadius(12)
                    .padding(.horizontal)
                    
                    SleepLinearTimelineView(samples: summary.samples)
                        .padding(.horizontal)

                    SleepHypnogramView(samples: summary.samples)
                        .padding(.horizontal)
                    
                    VStack(spacing: 0) {
                        Text("SLEEP STAGES")
                            .font(.caption)
                            .foregroundColor(.secondary)
                            .bold()
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.horizontal, 4)
                            .padding(.bottom, 8)
                        
                        VStack(spacing: 12) {
                            DetailedPhaseRow(title: "Awake", duration: summary.awakeDuration, color: .orange)
                            Divider()
                            DetailedPhaseRow(title: "REM (Быстрый)", duration: summary.remDuration, color: .purple)
                            Divider()
                            DetailedPhaseRow(title: "Core (Базовый)", duration: summary.coreDuration, color: .blue)
                            Divider()
                            DetailedPhaseRow(title: "Deep (Глубокий)", duration: summary.deepDuration, color: .indigo)
                        }
                        .padding()
                        .background(Color(.secondarySystemBackground))
                        .cornerRadius(12)
                    }
                    .padding(.horizontal)
                    
                } else {
                    VStack(spacing: 15) {
                        Spacer(minLength: 50)
                        Image(systemName: "moon.stars.fill")
                            .font(.system(size: 64))
                            .foregroundColor(.secondary.opacity(0.5))
                        
                        Text("No Sleep Data")
                            .font(.headline)
                        
                        Text("No sleep records were detected in HealthKit or generated by the simulator for this day.")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 30)
                        Spacer()
                    }
                }
                
            }
            .padding(.top, 10)
        }
        .background(Color(.systemGroupedBackground).ignoresSafeArea())
        .navigationTitle(formatter.string(from: date))
        .navigationBarTitleDisplayMode(.inline)
    }
    
    private func formatTimeInHoursAndMinutes(_ interval: TimeInterval) -> String {
        let hours = Int(interval) / 3600
        let minutes = (Int(interval) % 3600) / 60
        if hours > 0 {
            return "\(hours)h \(minutes)m"
        } else {
            return "\(minutes)m"
        }
    }
}

struct DetailedPhaseRow: View {
    let title: String
    let duration: TimeInterval
    let color: Color
    
    var body: some View {
        HStack(spacing: 12) {
            Circle()
                .fill(color)
                .frame(width: 12, height: 12)
            
            Text(title)
                .font(.body)
                .foregroundColor(.primary)
            
            Spacer()
            
            Text(formatTime(duration))
                .font(.body)
                .bold()
                .foregroundColor(.secondary)
        }
    }
    
    private func formatTime(_ interval: TimeInterval) -> String {
        let hours = Int(interval) / 3600
        let minutes = (Int(interval) % 3600) / 60
        if hours > 0 {
            return "\(hours)h \(minutes)m"
        } else {
            return "\(minutes)m"
        }
    }
}
